name: Deploy to Glitch branch

on:
  workflow_run:
    workflows: ["Cypress Tests"]
    types:
      - completed
    branches:
      - main
  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout Glitch branch
        uses: actions/checkout@v3
        with:
          ref: glitch

      - name: Use Node.js (match Glitch's version)
        uses: actions/setup-node@v2
        with:
          node-version: '16.x' # Replace with the Node.js version Glitch is using
  
      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
      
      - name: Debugging - List contents of the dist directory
        run: |
          echo "Listing contents of the dist directory:"
          ls -la dist/
          echo "Current working directory:"
          pwd

      - name: Check for changes
        id: git-check
        run: |
          git status
          if git diff --quiet && git diff --staged --quiet; then
            echo "No changes to commit."
            echo "::set-output name=changes_exist::false"
          else
            echo "Changes detected."
            echo "::set-output name=changes_exist::true"
          fi

      - name: Commit and push if changes exist
        if: steps.git-check.outputs.changes_exist == 'true'
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add dist -f
          git add -A
          git commit -m "Add build artifacts"

      - name: Push to Glitch branch
        run: git push origin glitch --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}