name: Deploy to Glitch

on:
  push:
    branches:
      - glitch

jobs:
  sync-with-glitch:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout the code
        uses: actions/checkout@v3
        with:
          ref: 'glitch' # The branch you want to deploy
        
      - name: Sync with Glitch
        uses: wei/git-sync@v3.0.0
        with:
          source_repo: https://${{ secrets.GITHUB_TOKEN }}@/github.com/someaka/graphblur.git
          source_branch: "glitch"
          destination_repo: ${{ secrets.GLITCH_GIT_URL }}
          destination_branch: "master"
